### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BrenuDev** [mobizt/HTTPClientESP32Ex#2]
Hi 

I've updated my project with the latest version of this library.
Since then it keeps crashing when I try to send an email.
![image](https://user-images.githubusercontent.com/8317833/62777468-e96f3a00-baad-11e9-83b9-d1b042fcf239.png)
This is the crash

**Comment by mobizt** [comment]
For ESP32 Mail Client library, you need to update to the latest version, 2.0.x. For HTTPClientESP32Ex, it is not required to install separately for ESP32 Mail Client library anymore, you can now delete it from libraries.

**Comment by BrenuDev** [comment]
Oh interesting thanks!
Will give it a try

**Comment by BrenuDev** [comment]
I only see version 1.2.1 for the ESP32 Mail Client.

**Comment by mobizt** [comment]
Sorry, I don't remember it exactly. That is the latest version.

**Comment by BrenuDev** [comment]
Ok thanks!
I did some further testing.
Will open an issue at the ESP32 Mail Client Repo
