### ISSUE TITLE
Can you please explain how to do this

### ISSUE THREAD

**Issue by hansdiaz** [mobizt/HTTPClientESP32Ex#3]
in my code, I'm already sending data to firebase, and I cannot use the default HTTPClient library along with it, so i believe this is the alternative for it. sir, could you please give me an example of how to do it.

let's say if I'm trying to send a POST request of json payload like {"device":"devicename"} to an address as https://sample.herokuapp.com/path/ how can I put the related code, 

I already read the readme file but couldn't understand it, also should I externally attach this library or does it already comes with the  FirebaseESP32 library?

please I really appreciate your help

**Comment by mobizt** [comment]
No need to use this library.

If want to use the internal WiFiClient of Firebase Data object for external usage, just use
```C++

  //If you declare the Firebase Data object like this
  FirebaseData firebaseData;


  firebaseData.pauseFirebase(true);
  WiFiClient client = firebaseData.getWiFiClient();
  if (client.connect("sample.herokuapp.com", 443))
  {
    Serial.println("Server connected");

    client.print("GET /path HTTP/1.1\r\n");             // should end with CRLF (\r\n) for each line of header
    client.print("Content-Type: application/json\r\n"); //should end with CRLF (\r\n) for each line of header
    //Other http header

    //client.print("Content-Length: xxxxx\r\n");//use only incase of POST and PATCH where xxxxx is the length of post data
    client.print("\r\n"); //End the header with extras CRLF
    //Your post data begin here
    //client.print(stringData);
    
    //This waiting for data in the rx buffer to be ready (necessary for the TLS synchronous data transmission) 
    while (client.connected() && client.available() <= 0)
    {
      delay(0);
      //check for waiting timeout here
    }

    while (client.connected() && client.available() > 0)
    {
      size_t availableread = client.available();
      char *myData = new char[availableread + 1];
      memset(myData, 0, availableread + 1);

      int actualRead = client.readBytes((uint8_t *)myData, availableread);

      if (actualRead == availableread)
      {
        //Success reading the payload
        Serial.println(myData);
      }
      else
      {
        //something or communication error
        Serial.println("Data is incompleted");
      }
    }

    client.stop(); //in case where you don't want to send eany data anymore which the memory will be released
  }

  firebaseData.pauseFirebase(false); //resume the Firebase Data object for its normal operations

```

You can test to make the http/https connection with [postman](https://www.postman.com/downloads/) which I also use it too.

**Comment by hansdiaz** [comment]
Thank you very much, sir, I have included the above code as such in my code using ArduinoJSON to send it as a JSON post request, this code is not wrong, am I? 

```
void sendRequest(){

  char jsonOutput[128];

  const size_t CAPACITY = JSON_OBJECT_SIZE(1);
  StaticJsonDocument<CAPACITY> doc;

  JsonObject object =doc.to<JsonObject>();
  object["device"]="11001125";
  serializeJson(doc, jsonOutput);
  
  
  firebaseData.pauseFirebase(true);
  WiFiClient client = firebaseData.getWiFiClient();
  if (client.connect("e-b-t.herokuapp.com", 443))
  {
    Serial.println("Server connected");

    client.print("POST /linkingdevices HTTP/1.1\r\n");             // should end with CRLF (\r\n) for each line of header
    client.print("Content-Type: application/json\r\n"); //should end with CRLF (\r\n) for each line of header
    //Other http header

    client.print("Content-Length: 1000\r\n");//use only incase of POST and PATCH where xxxxx is the length of post data
    client.print("\r\n"); //End the header with extras CRLF
    //Your post data begin here
     int dataSize= 1000;
    client.write(String(jsonOutput), dataSize);
    client.print("\r\n");//End the payload data with extras CRLF

    while (client.connected() && client.available() <= 0)
    {
      delay(0);
      //check for waiting timeout here
    }

    while (client.connected() && client.available() > 0)
    {
      size_t availableread = client.available();
      char *myData = new char[availableread + 1];
      memset(myData, 0, availableread + 1);

      int actualRead = client.readBytes((uint8_t *)myData, availableread);

      if (actualRead == availableread)
      {
        //Success reading the payload
        Serial.println(myData);
      }
      else
      {
        //something or communication error
        Serial.println("Data is incompleted");
      }
    }

    client.stop(); //in case where you don't want to send eany data anymore which the memory will be released
  }

  firebaseData.pauseFirebase(false); //resume the Firebase Data object for its normal operations
}
```

an error pops out when im using int variable for data size as  error: no matching function for call to 'WiFiClient::write(String, int&)'  client.write(String(jsonOutput),dataSize );

**Comment by mobizt** [comment]
I'm never test it yet.

The payload length and the content length header should match otherwise the sever will waiting the data to be completely received unless the timeout occurred.

Recommend for char array preparation
```C++
char jsonOutput[128];
memset(jsonOutput,0, 128);//fill the array with 0 for treat it as a zero length string
```
Due to I don't know about the actual string length stored in the jsonOutput, construct new string from its value.
```C++
String payload = jsonOutput; 
```

Modified content length header
```C++
client.print("Content-Length: ");
client.print(payload.length());
client.print("\r\n");
```
For payload sending
```C++
client.print(payload.c_str()); //get the internal constant char array from string object and print (only string)
```

Please be careful, when use the function, write, when you write the data contains 0 value in some byte of data which is null, the termination of string, the data received by server will count the data only before 0 byte existed, which will be shorter than the length provided in the header.
 
To avoid this problem, use print instead which will only send the string  to server (no null data included).

**Comment by mobizt** [comment]
I tell some wrong info, don't need to send CRLF after finish the payload sending
 //client.print("\r\n");//End the payload data with extras CRLF

I will remove it from my first comment above

**Comment by hansdiaz** [comment]
Thank you for your reply, if I am to send a get with a parameter the only thing i need to do is to add a code like this right?

```
String variable="110112";
client.print("GET/linkingdevices/"+String(variable)+" HTTP/1.1\r\n");
```

and only that would be needed right?

**Comment by mobizt** [comment]
Don't join the string object, it's complicated and can make the fragmentation of memory as it is a class. 
Separate them and send each are better.

```C++
client.print("GET /linkingdevices/"); //space should be followed by GET
client.print(variable.c_str());
client.print(" HTTP/1.1\r\n");//space should be in front of HTTP/1.1
```

**Comment by hansdiaz** [comment]
Thank you sir,  you literally saved me today.

**Comment by hansdiaz** [comment]
By the way this code would be looking out for a 200 response from the server, right? so that means my back end is an express node js server so I would keep this code in another core since it would wait for the response, if so would having another FirebaseData object fix at running this code (function) on core 0? or would it show exceptions.

I updated the server code to not send a response and it still works out pretty perfectly in the node mcu without much lag, i guess its not waiting in this code you have mentioned.


```
while (client.connected() && client.available() > 0)
    {
      size_t availableread = client.available();
      char *myData = new char[availableread + 1];
      memset(myData, 0, availableread + 1);

      int actualRead = client.readBytes((uint8_t *)myData, availableread);

      if (actualRead == availableread)
      {
        //Success reading the payload
        Serial.println(myData);
      }
      else
      {
        //something or communication error
        Serial.println("Data is incompleted");
      }
    }
```

**Comment by mobizt** [comment]
Every new establish https connection, it requires the time for SSL/TLS handshaking process (sometime almost a second) which you need to wait and any consequence request/response will be faster if the connection is keep alive.

I think that the lag you mention is because I mention above which is the normal behavior of https protocol which you feel lag or delay because the last connection is closed and need to perform SSL/TLS handshake again when you called **client.connect**.

You can comment out this code **client.stop();** and add the header

```C++
client.print("Connection: keep-alive\r\n");
```
Don't mention about async http client in this limited memory and has only one RF channel device which even it does not need to wait for the responses but open the multiple socket connections will consume more memory which required to handle each request/response.

**Comment by mobizt** [comment]
For the HTTP response code you need to do more study (or search the google).

**Comment by hansdiaz** [comment]
I have a problem, I ran the node MCU and it prints that it connected to the server, but I couldn't test it since my backend was hosted on Heroku, so I tested by triggering a simple JSON save in the realtime firebase, but it doesn't send the get request to the back end server. (I tested the backend function with a simple get request using postman and it works a charm but for the esp32 its not)

I added a delay of 1000 here but it still doesn't work

```
while (client.connected() && client.available() <= 0)
    {
      delay(1000);
      //check for waiting timeout here
    }
```
also my output only shows 

Server connected

it doesn't show the outputs of this code
```
while (client.connected() && client.available() > 0)
    {
      size_t availableread = client.available();
      char *myData = new char[availableread + 1];
      memset(myData, 0, availableread + 1);

      int actualRead = client.readBytes((uint8_t *)myData, availableread);

      if (actualRead == availableread)
      {
        //Success reading the payload
        Serial.println(myData);
      }
      else
      {
        //something or communication error
        Serial.println("Data is incompleted");
      }
    }
```

**Comment by mobizt** [comment]
If you can make a request with postman you also can do it in the device too.

Check your header and payload, you also can view the code in postman.
